linters:
  disable-all: true
  enable:
    - copyloopvar
    - errcheck
    - gci
    - gosimple
    - govet
    - grouper
    - ineffassign
    - staticcheck
    - unused
    - stylecheck
    - whitespace
issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
linters-settings:
  gci:
    sections:
      - standard
      - default
      - localmodule
  gofmt:
    rewrite-rules:
      - pattern: 'interface{}'
        replacement: 'any'
  grouper:
    import-require-single-import: true
    import-require-grouping: true
    const-require-grouping: true
    var-require-grouping: true
  whitespace:
    multi-func: true
    multi-if: true