linters:
  disable-all: true
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - contextcheck
    - copyloopvar
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - exhaustruct
    - forcetypeassert
    - gci
    - ginkgolinter
    - gocheckcompilerdirectives
    - goconst
    - godot
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - grouper
    - inamedparam
    - ineffassign
    - makezero
    - mirror
    - misspell
    - musttag
    - nakedret
    - noctx
    - usestdlibvars
    - nolintlint
    - nosprintfhostport
    - predeclared
    - protogetter
    - recvcheck
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - testableexamples
    - testpackage
    - unparam
    - unused
    - wastedassign
    - whitespace
linters-settings:
  exhaustive:
    check:
      - switch
      - map
    explicit-exhaustive-switch: true
    explicit-exhaustive-map: true
  gci:
    sections:
      - standard
      - default
      - localmodule
  ginkgolinter:
    forbid-spec-pollution: true
    force-expect-to: true
  godot:
    scope: toplevel
    capital: true
  gofmt:
    rewrite-rules:
      - pattern: 'interface{}'
        replacement: 'any'
  gosec:
    excludes:
      - G103
      - G104
      - G204
      - G301
      - G302
      - G304
      - G307
  grouper:
    import-require-single-import: true
    import-require-grouping: true
    const-require-grouping: true
    var-require-grouping: true
  inamedparam:
    skip-single-param: false
  nakedret:
    max-func-lines: 1
  whitespace:
    multi-func: true
    multi-if: true
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-use-default: false
  exclude-rules:
    - path: '_test\.go'
      linters:
        - exhaustruct
        - forcetypeassert
        - goconst